CONCLUSIVE_RESULT_MULTIPLIER = 1000
TEMPERATURE_CONTROL_FOR_MAX_RANDOMNESS = 1000
# Setting an extremely small value since putting 0 gives division error
TEMPERATURE_CONTROL_FOR_MIN_RANDOMNESS = 1e-6
MAX_MOVE_COUNT_WITH_INITIAL_TEMPERATURE_CONTROL = 5
MIN_GAME_SIMULATION_BENCHMARK = 1000
MIN_GAME_SIMULATION_BENCHMARK_MCTS = 50
UPPER_BOUND_CONFIDENCE_1_CONSTANT = 2
MOVE_X = "X"
MOVE_O = "O"