CONCLUSIVE_RESULT_MULTIPLIER = 1000
TEMPERATURE_CONTROL_FOR_MAX_RANDOMNESS = 1
# Setting an extremely small value since putting 0 gives division error
TEMPERATURE_CONTROL_FOR_MIN_RANDOMNESS = 1e-6
MAX_MOVE_COUNT_WITH_INITIAL_TEMPERATURE_CONTROL = 5
MIN_GAME_SIMULATION_BENCHMARK = 1000